USE ;
SELECT * FROM sysfiles 
GO;

DECLARE @DATA_BASE VARCHAR(255) = 'SISCOMEX_DASCAM_0411'
DECLARE @SQL_LOG VARCHAR(255) = 'Siscomex_log'
DECLARE @SQL_CLEAR VARCHAR(MAX) = ''

SET @SQL_CLEAR = ' ALTER DATABASE [' + @DATA_BASE + ']';
SET @SQL_CLEAR = @SQL_CLEAR + ' SET RECOVERY SIMPLE; ';
SET @SQL_CLEAR = @SQL_CLEAR + ' DBCC SHRINKFILE (''' + @SQL_LOG +  ''', 1); ';
SET @SQL_CLEAR = @SQL_CLEAR + ' ALTER DATABASE [' + @DATA_BASE + ']';
SET @SQL_CLEAR = @SQL_CLEAR + ' SET RECOVERY FULL; ';

EXEC(@SQL_CLEAR)
