SELECT 
   BASES.NAME AS [NOME BASE],
   FILES.PHYSICAL_NAME, 
   FILES.TYPE_DESC AS [Tipo Descricao],
   (SIZE * 8) / 1024 [Tamanho (Mb)],     
   (SIZE * 8) / 1024 / 1024 [Tamanho (Gb)]
FROM SYS.DATABASES AS BASES
JOIN SYS.MASTER_FILES AS FILES ON FILES.DATABASE_ID = BASES.DATABASE_ID
